sudo: false
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.9
    - g++-4.9
    - uuid-dev
    - libssl-dev
language: node_js
node_js:
- '5'
env:
  global:
  - ZMQ="3.2.5"
  matrix:
  - GROUP=unit
  - GROUP=functional
  - GROUP=performance

cache:
  apt: true
  directories:
    - node_modules
    - zeromq-$ZMQ

before_install:
  - source travis_before_install
  - pip install jupyter_console --user
  - jupyter kernelspec install-self --user

install: env LD_LIBRARY_PATH=$LDHACK/lib LD_RUN_PATH=$LDHACK/lib PKG_CONFIG_PATH=$LDHACK/lib/pkgconfig LDFLAGS=-L$LDHACK/lib CFLAGS=-I$LDHACK/lib/include npm install

before_script:
- export DISPLAY=:99.0; sh -e /etc/init.d/xvfb start
script: travis_retry npm run test:$GROUP
after_success: npm run coverage
